name: newsitetest
favicon: null
layout_spectrum: 0.1787514218594879
typography_spectrum: 0.8509224012959749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1661832055542618
  lightness: 0.24698272231034935
  saturation: 0.07275404571555555
  rhythmicContrast: 0.8208777420222759
purpose: []
